In [8]:
import numpy as np

data_NYC = np.load('D:\\omer\\ST-SSL\\data\\NYCBike1\\train_new.npz')
for file in data_NYC.files:
    print(file, data_NYC[file].shape)

print(data_NYC['x_offsets'])
print(data_NYC['y_offsets'])

x (1813, 19, 128, 2)
y (1813, 1, 128, 2)
x_offsets (19, 1)
y_offsets (1, 1)
[[-73]
 [-72]
 [-71]
 [-70]
 [-69]
 [-49]
 [-48]
 [-47]
 [-46]
 [-45]
 [-25]
 [-24]
 [-23]
 [-22]
 [-21]
 [ -3]
 [ -2]
 [ -1]
 [  0]]
[[1]]


In [86]:
# import torch
# import numpy as np
# def smart_permute(n, X, metadata, delta=2):
#     """
#     Generate a permutation of indices for a tensor, ensuring that all samples
#     not end up within ± `delta` of its original position (from metadata).

#     Parameters:
#     - n: Total number of samples in the batch.
#     - X: The tensor to be permuted.
#     - metadata: Tensor containing the original indices of the samples.
#     - delta: The range (as defined by the metadata array) within which the new index for the samples in X should not fall.

#     Returns:
#     - Tensor X permuted satisfying the constraints.
#     """
#     valid_index=0
#     perm = np.zeros(n, dtype=int)
#     for i in range(n): # in this loop we will set perm[i]
#         print(f"valid indices for {i} are: ")
#         for j in range(i, n): # in this loop we will check all other indices to find valid index for perm[i]     
#             diff = abs(metadata[i] - metadata[j])
#             if diff % 24 not in [0, 1, 2, 22, 23]: 
#                 print(f"j: {j}")
#                 # print(abs(metadata[i] - metadata[j]), abs(metadata[i] - metadata[j])%24)
#                 valid_index=j
#         perm[i] = valid_index
#     X = X[perm]
        
        

#     return X



In [368]:
import torch
import numpy as np
def smart_permute(n, X, metadata, delta=2):
    """
    Generate a permutation of indices for a tensor, ensuring that all samples
    not end up within ± `delta` of its original position (from metadata).
    Parameters:
    - n: Total number of samples in the batch.
    - X: The tensor to be permuted.
    - metadata: Tensor containing the original indices of the samples.
    - delta: The range (as defined by the metadata array) within which the new index for the samples in X should not fall.

    Returns:
    - Tensor X permuted satisfying the constraints.
    """
    # valid_indeces=np.array([])
    perm = np.zeros(n, dtype=int)
    indices = np.arange(0, n)
    for i in range(0, n): # in this loop we will set perm[i]
             
        diff = abs(metadata[i] - metadata)
        mask = ~np.isin(diff % 24, [0, 1, 2, 22, 23])
        # Apply the mask to 'indices' to filter out the invalid indices
        valid_indices = indices[mask]
        # valid_indeces = indices[diff % 24 not in [0, 1, 2, 22, 23]]
        
        if len(valid_indices) > 0: 
            t =  np.random.choice(valid_indices)
        else:
            t = np.random.choice(indices)
            print("could not find heterogeneous sample")
        perm[i] = t
    return perm



In [96]:
a=np.array([0, 1, 2])
s = np.random.choice(a)
print(s)

2


In [97]:
for i in range(0, 30):
    if i % 24 > 2 and i % 24 < 22:
        print(i)

3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
27
28
29


In [98]:
idx=smart_permute(8, np.array([1, 2, 3, 4, 5, 6, 7, 8]), np.array([0, 3, 21, 24, 50, 49, 29, 7]), 2)
print(idx)

valid indices for 0 are: 
j: 1
j: 2
j: 4
j: 6
j: 7
valid indices for 1 are: 
j: 2
j: 3
j: 6
j: 7
valid indices for 2 are: 
j: 3
j: 4
j: 5
j: 6
j: 7
valid indices for 3 are: 
j: 4
j: 6
j: 7
valid indices for 4 are: 
j: 6
j: 7
valid indices for 5 are: 
j: 6
j: 7
valid indices for 6 are: 
valid indices for 7 are: 
[8 8 8 8 8 8 8 8]


In [581]:
idx=smart_permute(8, np.array([1, 2, 3, 4, 5, 6, 7, 8]), np.array([5, 24, 24, 24, 24, 24, 24, 24]), 2)
print(idx)

[7 1 1 1 1 1 1 1]


In [69]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
