In [1]:
import numpy as np
adj = "data/NYCTaxi/pretrained_adj_mx.npz"
adj = np.load(adj)["adj_mx"]
print(adj)

[[0.00244035 0.00260635 0.00290332 ... 0.0049551  0.00517954 0.00508961]
 [0.00234594 0.00251868 0.00282366 ... 0.00495759 0.00519514 0.00509214]
 [0.00228778 0.0024695  0.00278735 ... 0.00497099 0.00521594 0.00510543]
 ...
 [0.00219833 0.00237579 0.00270192 ... 0.00495554 0.0052113  0.0050734 ]
 [0.00221728 0.00240214 0.00273169 ... 0.00496576 0.00522754 0.0050868 ]
 [0.00225404 0.00244504 0.00278051 ... 0.00496684 0.0052338  0.00510117]]


In [1]:
import numpy as np
a = np.load(r"D:\omer\ST-SSL\data\NYCTaxi\adj_mx.npz")
print(a.files)
# np.savez(r"D:\omer\ST-SSL\data\NYCTaxi\pretrained_adj_mx.npz", adj_mx=a)

['attn1']


In [21]:
import numpy as np

data_NYC = np.load('D:\\omer\\ST-SSL\\data\\NYCBike2\\train.npz')
# for file in data_NYC.files:
#     print(f"{file}: shape: {data_NYC[file].shape}")

print("x_offsets: ", data_NYC['x_offsets'][:])
# print("y_offsets: ", data_NYC['y_offsets'][:])
# print(data_NYC['y_offsets'])
for split in ['train', 'test', 'val']:
    data= np.load('D:\\omer\\ST-SSL\\data\\NYCBike2\\{}.npz'.format(split))
    print(f"{split}: ", data['x'].shape)

x_offsets:  [[-147]
 [-146]
 [-145]
 [-144]
 [-143]
 [-142]
 [-141]
 [-140]
 [-139]
 [ -99]
 [ -98]
 [ -97]
 [ -96]
 [ -95]
 [ -94]
 [ -93]
 [ -92]
 [ -91]
 [ -51]
 [ -50]
 [ -49]
 [ -48]
 [ -47]
 [ -46]
 [ -45]
 [ -44]
 [ -43]
 [  -7]
 [  -6]
 [  -5]
 [  -4]
 [  -3]
 [  -2]
 [  -1]
 [   0]]
train:  (1912, 35, 200, 2)
test:  (546, 35, 200, 2)
val:  (274, 35, 200, 2)


In [31]:
input_length="A"
input_sequence_dict = {"A":[-8, 35], "B":[-17, -8], "C":[-26, -17], "D":[-35, -26]}
input_sequence = input_sequence_dict[input_length]
# skip = cat_data['x'].shape[1] - input_length
print(data_NYC['x_offsets'][input_sequence[0]:input_sequence[1]])

# print("x_offsets: ", data_NYC['x_offsets'][-19:-14])

[[-7]
 [-6]
 [-5]
 [-4]
 [-3]
 [-2]
 [-1]
 [ 0]]


In [17]:
import numpy as np

# Base directory where the files are located
base_dir = 'D:\\omer\\ST-SSL\\data\\NYCBike1\\'

# Loop through each split and process the files
for split in ['train', 'test', 'val']:
    # Load the data
    file_path = f'{base_dir}{split}.npz'
    data = np.load(file_path)
    
    # Extract the 'x' data and remove the first 5 samples from it
    x_data = data['x']
    x_modified = x_data[:, 5:, :, :]  # Assuming the samples to remove are along the second axis
    
    # Save the modified data into a new .npz file
    new_file_path = f'{base_dir}{split}_14.npz'
    np.savez(new_file_path, x=x_modified, y=data['y'], x_offsets=data['x_offsets'][5:], y_offsets=data["y_offsets"])  # Assuming you want to keep 'y' unchanged
    
    print(f"Processed {split}: Original shape {data['x'].shape}, New shape {x_modified.shape}")


Processed train: Original shape (1813, 19, 128, 2), New shape (1813, 14, 128, 2)
Processed test: Original shape (2074, 19, 128, 2), New shape (2074, 14, 128, 2)
Processed val: Original shape (431, 19, 128, 2), New shape (431, 14, 128, 2)


In [6]:
import numpy as np
arr = np.random.randn(10, 19, 21)

arr2 = arr[:, 5:24, :]
print(arr2.shape)

(10, 14, 21)


In [7]:
35-8

27